---

- name: Cleaning "{{ bank_name }}" blast+ indexes links
  become: yes
  become_user: "{{ bank_user }}"
  file: 
    path={{ bank_root }}/index/blast+/{{ blast_plus_vers }}/{{ item | basename }} 
    state=absent
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast+/{{ blast_plus_vers }}/*.[np]??"  

