---
- name: Creating links to blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  file: >
    src={{ item }}
    dest={{bank_root}}/index/blast2/{{ blast2_vers }}/{{ item | basename }}
    state=link
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast+/*.[np]??"


