---
################################################################################
# Bio-DAMNED - Bio-Data Ansible MaNagED                                        #
#                                                                              #
# Authors: Bertrand Néron                                                      #
# Copyright © 2016  Institut Pasteur (Paris).                                  #
#                                                                              #
# Bio-DAMNED is distributed under the terms of the GNU General Public License  #
# (GPLv3). See the LICENSE file for details.                                   #
################################################################################

- name: Download and index banks
  hosts: banks
  remote_user: root

  roles:
    - {role: genbank_genome, tags: ['cdc1551'],
       bank_name: m_tuberculosis_CDC1551,
       bank_src: "ftp://ftp.ncbi.nih.gov/genomes/archive/old_genbank/Bacteria/Mycobacterium_tuberculosis_CDC1551_uid223/AE000516.gbk"}
    - {role: fasta_genome, tags: ['yersinia'],
       bank_name: yersinia_pestis,
       bank_src: "ftp://ftp.ncbi.nih.gov/genomes/refseq/bacteria/Yersinia_pestis/reference/GCF_000009065.1_ASM906v1/GCF_000009065.1_ASM906v1_genomic.fna.gz",
       large: false}
    - {role: silva_bank, tags: ['silva_LSU', 'silva'],
       bank_name: silva,
       bank_src: ["ftp://ftp.arb-silva.de/current/Exports/SILVA_128_SSURef_Nr99_tax_silva.fasta.gz",
                  "ftp://ftp.arb-silva.de/current/Exports/SILVA_128_LSURef_tax_silva.fasta.gz"]}
    - {role: greengenes_bank, tags: ['greengenes'],
       bank_name: greengenes,
       bank_src: "ftp://greengenes.microbio.me/greengenes_release/current/gg_13_5_with_header.fasta.gz"}
    - {role: blast_bank, tags: ['ncbi_16s'],
       bank_name: ncbi_16s,
       bank_src: "ftp://ftp.ncbi.nih.gov/blast/db/16SMicrobial.tar.gz"}
    - {role: fasta_bank, tags: ['nt'],
       bank_name: nt,
       bank_src: "ftp://ftp.ncbi.nih.gov/blast/db/FASTA/nt.gz"}
    - {role: genbank_bank, tags: ['swissprot'],
       bank_name: swissprot,
       bank_src: "ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz",
       dbtype: 'prot'}
    - {role: frogs, tags: ['frogs'],
       bank_name: frogs,
       bank_src: ["http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/16S/silva_123_16S.tar.gz", 
                  "http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/18S/silva_119-1_18S.tar.gz", 
                  "http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/18S/silva_123_18S.tar.gz", 
                  "http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/23S/silva_123_23S.tar.gz"]}
    - {role: taxodb_bank, tags: ['taxodb'],
       bank_name: taxodb,
       bank_src: "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz"}
    - {role: prosite, tags: ['prosite'],
       bank_name: prosite,
       bank_src: ["ftp://ftp.expasy.ch/databases/prosite/prosite.dat",
                  "ftp://ftp.expasy.ch/databases/prosite/prosite.doc",
                  "ftp://ftp.expasy.ch/databases/prosite/prosite.lis"]
      } 
